nelson-lang/nelson

CHANGELOG.md, modules/core/CMakeLists.txt, modules/core/builtin/c/nlsCore_builtin.vcxproj, modules/core/builtin/c/nlsCore_builtin.vcxproj.filters, modules/core/builtin/cpp/Gateway.cpp, modules/core/builtin/cpp/maxNumCompThreadsBuiltin.cpp, modules/core/builtin/include/maxNumCompThreadsBuiltin.hpp, modules/core/help/en_US/xml/maxNumCompThreads.xml, modules/core/src/c/nlsCore.vcxproj, modules/core/src/c/nlsCore.vcxproj.filters, modules/core/src/cpp/ComputionalThreads.cpp, modules/core/src/include/ComputionalThreads.hpp, modules/core/tests/test_maxNumCompThreads.nls, modules/engine/src/cpp/MainEvaluator.cpp, modules/fftw/builtin/cpp/fftBuiltin.cpp, modules/fftw/builtin/cpp/ifftBuiltin.cpp, modules/fftw/src/cpp/FftHelpers.cpp, modules/main/help/en_US/html/changelog.html, modules/main/help/fr_FR/html/changelog.html
fft & ifft are faster (but we could do better in another life ...)
add and use 'maxNumCompThreads'
=> Feature 59

.lgtm.yml, README.md
Hi team!
I noticed that you've recently enabled LGTM's automatic code review for pull requests, but that your C/C++ code wasn't being analysed. This `lgtm.yml` file should install the right dependencies that we couldn't automatically detect (working on a fix to the auto-detection); C/C++ results are on their way! If you ever need to tweak your build process for LGTM: https://lgtm.com/help/lgtm/cpp-extraction
This `lgtm.yml` also lists some modules as 'library' code — do add more if you think I've missed some. You obviously know the code base much better than me. Last but not least: an LGTM badge :slightly_smiling_face: 
Feel free to tweak the PR!
=> Enable LGTM.com analysis for C/C++ code

CHANGELOG.md, ROADMAP.md, modules/elementary_functions/builtin/cpp/sizeBuiltin.cpp, modules/elementary_functions/help/en_US/xml/size.xml, modules/elementary_functions/tests/test_size.nls, modules/string/builtin/c/nlsString_builtin.vcxproj, modules/string/builtin/c/nlsString_builtin.vcxproj.filters, modules/string/builtin/cpp/Gateway.cpp, modules/string/builtin/cpp/matchesBuiltin.cpp, modules/string/builtin/include/matchesBuiltin.hpp, modules/string/help/en_US/xml/matches.xml, modules/string/src/c/nlsString.vcxproj, modules/string/src/c/nlsString.vcxproj.filters, modules/string/src/cpp/StringMatches.cpp, modules/string/src/include/StringMatches.hpp, modules/string/tests/test_matches.nls, modules/types/src/cpp/ArrayOf_Display.cpp, modules/types/src/cpp/ArrayOf_StringType.cpp
* matches builtin
* update size behavior
=> Matches, size

CHANGELOG.md, modules/elementary_functions/CMakeLists.txt, modules/elementary_functions/builtin/c/nlsElementary_functions_builtin.vcxproj, modules/elementary_functions/builtin/c/nlsElementary_functions_builtin.vcxproj.filters, modules/elementary_functions/builtin/cpp/Gateway.cpp, modules/elementary_functions/builtin/cpp/linspaceBuiltin.cpp, modules/elementary_functions/builtin/cpp/log10Builtin.cpp, modules/elementary_functions/builtin/cpp/log1pBuiltin.cpp, modules/elementary_functions/builtin/include/linspaceBuiltin.hpp, modules/elementary_functions/builtin/include/log10Builtin.hpp, modules/elementary_functions/builtin/include/log1pBuiltin.hpp, modules/elementary_functions/functions/logspace.nlf, modules/elementary_functions/help/en_US/xml/linspace.xml, modules/elementary_functions/help/en_US/xml/log10.xml, modules/elementary_functions/help/en_US/xml/log1p.xml, modules/elementary_functions/help/en_US/xml/logspace.xml, modules/elementary_functions/src/c/nlsElementary_functions.vcxproj, modules/elementary_functions/src/c/nlsElementary_functions.vcxproj.filters, modules/elementary_functions/src/cpp/Logarithm10.cpp, modules/elementary_functions/src/cpp/Logarithm1p.cpp, modules/elementary_functions/src/include/Logarithm10.hpp, modules/elementary_functions/src/include/Logarithm1p.hpp, modules/elementary_functions/tests/bench_linspace.nls, modules/elementary_functions/tests/test_linspace.nls, modules/elementary_functions/tests/test_log10.nls, modules/elementary_functions/tests/test_log1p.nls, modules/elementary_functions/tests/test_logspace.nls
=> Linspace & Logspace

modules/types/src/cpp/ArrayOf_Extract.cpp
{Please write here}
{Please write here}
{Please write here}
=> fix extract simple indexing 64 bits

CHANGELOG.md, modules/engine/CMakeLists.txt, modules/engine/builtin/c/nlsEngine_builtin.vcxproj, modules/engine/builtin/c/nlsEngine_builtin.vcxproj.filters, modules/engine/builtin/cpp/getpidBuiltin.cpp, modules/engine/builtin/include/getpidBuiltin.hpp, modules/engine/help/en_US/xml/getpid.xml, modules/engine/module.iss, modules/engine/src/c/nlsEngine.vcxproj, modules/engine/src/c/nlsEngine.vcxproj.filters, modules/engine/src/cpp/NelsonPIDs.cpp, modules/engine/src/cpp/StartNelson.cpp, modules/engine/src/include/NelsonPIDs.hpp, modules/engine/tests/test_getpid.nls
get current pid and all nelson's pid currently running !
=> getpid builtin

CHANGELOG.md, modules/elementary_functions/functions/ind2sub.m, modules/elementary_functions/functions/sub2ind.m, modules/elementary_functions/help/en_US/xml/ind2sub.xml, modules/elementary_functions/help/en_US/xml/sub2ind.xml, modules/elementary_functions/tests/test_ind2sub.m, modules/elementary_functions/tests/test_sub2ind.m
=> ind2sub, sub2ind functions

.circleci/config.yml
only one hours free on Circle CI
=> disable benchs on Circle CI

CHANGELOG.md, README.md, chocolatey/nelson/nelson.nuspec, chocolatey/nelson/tools/LICENSE.txt, chocolatey/nelson/tools/chocolateyinstall.ps1, chocolatey/nelson/tools/chocolateyuninstall.ps1, chocolatey/readme.md
=> fix #605 Chocolatey package

CHANGELOG.md, modules/engine/src/cpp/StartNelson.cpp, modules/stream_manager/builtin/cpp/sscanfBuiltin.cpp, modules/stream_manager/src/c/nlsStream_manager.vcxproj, modules/stream_manager/src/c/nlsStream_manager.vcxproj.filters, modules/stream_manager/src/cpp/FscanFunction.cpp, modules/stream_manager/src/cpp/SscanfFunction.cpp, modules/stream_manager/src/include/SscanfFunction.hpp, modules/stream_manager/tests/bench_sscanf.m, modules/stream_manager/tests/test_sscanf.m
sscanf manages unicode and is faster
=> sscanf unicode and rework - bench

modules/core/src/cpp/NelsonSHA256.cpp, modules/file_archiver/src/cpp/Zip.cpp, modules/files_folders_functions/src/cpp/FileDiff.cpp, modules/help_tools/builtin/cpp/htmltopdfBuiltin.cpp, modules/help_tools/src/cpp/HeadComments.cpp, modules/help_tools/src/cpp/ImageTagHelpers.cpp, modules/help_tools/src/cpp/QtHelpProject.cpp, modules/help_tools/src/cpp/XmlDocDocument.cpp, modules/help_tools/src/cpp/XmlDocMainIndex.cpp, modules/help_tools/src/cpp/XmlHelpers.cpp, modules/history_manager/src/cpp/HistoryManager.cpp, modules/interpreter/src/cpp/PathFuncManager.cpp, modules/localization/src/cpp/Localization.cpp, modules/modules_manager/src/cpp/ModulesManager.cpp, modules/modules_manager/src/cpp/ReadUserModules.cpp, modules/stream_manager/builtin/cpp/filewriteBuiltin.cpp, modules/stream_manager/src/cpp/Diary.cpp, modules/stream_manager/src/cpp/MapFileRead.cpp, modules/stream_manager/src/cpp/SscanfFunction.cpp, modules/text_editor/src/cpp/TextEditorPreferences.cpp
after last update on ArchLinux, nelson failed to build
=> fix archLinux build

.gitignore, CHANGELOG.md, modules/interpreter/src/cpp/MexFunctionDef.cpp, modules/mex/CMakeLists.txt, modules/mex/examples/rust-mex-builder/README.md, modules/mex/examples/rust-mex-builder/helloworld/Cargo.toml, modules/mex/examples/rust-mex-builder/helloworld/build.template, modules/mex/examples/rust-mex-builder/helloworld/src/lib.rs, modules/mex/module.iss
Example to build mexfunction using Rust
=> Building MexFunction using Rust

CHANGELOG.md, modules/text_completion/src/cpp/VariableCompleter.cpp, modules/text_editor/tests/bug_github_issue_#834.m
=> fix #834 VariableCompleter was not filtered by prefix.

.github/workflows/ccpp.yml
again :(
https://github.com/orgs/community/discussions/47863
=> fix ubuntu 22.04 CI

modules/terminal/src/cpp/BasicTerminal.cpp
=> fix unexpected exit with only carriage return

modules/elementary_functions/src/cpp/Exponential.cpp
=> fix warning detected with codeql

CHANGELOG.md, modules/core/builtin/cpp/narginBuiltin.cpp, modules/core/builtin/cpp/nargoutBuiltin.cpp, modules/display_format/src/c/nlsDisplay_format.vcxproj, modules/display_format/src/c/nlsDisplay_format.vcxproj.filters, modules/display_format/src/cpp/DisplayVariable.cpp, modules/display_format/src/cpp/DisplayVariableHelpers.cpp, modules/display_format/tests/test_display_function_handle.m, modules/function_handle/CMakeLists.txt, modules/function_handle/builtin/c/nlsFunction_handle_builtin.vcxproj, modules/function_handle/builtin/c/nlsFunction_handle_builtin.vcxproj.filters, modules/function_handle/builtin/cpp/Gateway.cpp, modules/function_handle/builtin/cpp/func2strBuiltin.cpp, modules/function_handle/builtin/cpp/function_handle_displayBuiltin.cpp, modules/function_handle/builtin/cpp/str2funcBuiltin.cpp, modules/function_handle/builtin/include/function_handle_displayBuiltin.hpp, modules/function_handle/builtin/include/str2funcBuiltin.hpp, modules/function_handle/src/c/nlsFunction_handle.vcxproj, modules/function_handle/src/c/nlsFunction_handle.vcxproj.filters, modules/function_handle/src/cpp/DisplayFunctionHandle.cpp, modules/function_handle/src/cpp/StringToFunctionHandle.cpp, modules/function_handle/src/include/DisplayFunctionHandle.hpp, modules/function_handle/src/include/StringToFunctionHandle.hpp, modules/function_handle/tests/test_str2func.m, modules/hdf5/src/cpp/h5SaveFunctionHandle.cpp, modules/interpreter/src/cpp/AnonymousMacroFunctionDef.cpp, modules/mpi/src/cpp/MPI_helpers.cpp
=> func2str and function_handle display reworked

CHANGELOG.md, modules/gui/src/cpp/QtTerminal.cpp, modules/gui/src/cpp/QtTerminal.h, modules/help_browser/src/cpp/HelpViewer.cpp, modules/help_browser/src/cpp/HelpViewer.h, modules/text_editor/src/cpp/QtTextEdit.cpp, modules/text_editor/src/cpp/QtTextEdit.h, modules/text_editor/src/cpp/QtTextEditor.cpp, modules/text_editor/src/cpp/QtTextEditor.h, resources/export-to.svg
CTRL + "+/-" zoom on console, editor, help
=> export to pdf/html console

CHANGELOG.md, modules/python_engine/src/cpp/PythonLibraryWrapper.cpp, modules/python_engine/src/cpp/PythonTypesWrapper.cpp, modules/python_engine/tests/bug_github_issue_#1148.m
=> fix #1148 - pyrun('print(A)','A','A',string(NaN)) did not return expected value.

BUILDING_Windows.md, modules/python_engine/src/cpp/PythonRunner.cpp, modules/python_engine/tests/test_pyrun_error_buffer.m
Update build instruction for Windows
=> Update build instruction for Windows

modules/control_system/functions/bode.m
=> Fix #1210 - Unwrap phase in "bode" function

.github/workflows/ccpp.yml, CHANGELOG.md, CMake/FindTBB.cmake, CMake/OptionsConfig.cmake, CMakeLists.txt, THIRDPARTY.md, docker/Dockerfile_Arch, docker/Dockerfile_Debian, docker/Dockerfile_Fedora, modules/commons/src/include/nlsBuildConfig.h.in, modules/commons/src/include/nlsBuildConfig.h.vc, snap/snapcraft.yaml
Prepares some others changes ...
TBB is great and optional in Nelson
=> optional use of TBB

.github/workflows/ccpp.yml, modules/ipc/src/cpp/NelsonInterprocess.cpp, modules/os_functions/src/cpp/SystemCommand.cpp, modules/os_functions/src/cpp/SystemCommandTask.cpp, modules/os_functions/src/cpp/SystemCommandTask.hpp, modules/os_functions/tests/test_system_3.m
remove BS threadpool use with system command
=> Fix system on Windows 32 bits 

.github/workflows/ccpp.yml, .github/workflows/mamba.yml, .github/workflows/minimal.yml, CHANGELOG.md, README.md, bin/macOS/nelson, modules/fftw/src/cpp/FFTWWrapper.cpp
Fixes #1259
Sequoia version seems more mature :)
=> Fix #1259 - Add macOS Sequoia and remove macOS Monterey CI support

CHANGELOG.md, modules/table/functions/@table/subsasgn.m, modules/table/functions/@table/subsref.m, modules/table/functions/removevars.m, modules/table/functions/renamevars.m, modules/table/help/en_US/xml/removevars.xml, modules/table/help/en_US/xml/renamevars.xml, modules/table/tests/test_removars.m, modules/table/tests/test_renamevars.m
- Implements renamevars() to rename table variables
- Implements removevars() to remove table variables
- Updates subsasgn and subsref table methods
- Adds documentation and tests
=> Fix #1248: add renamevars and removevars functions

CHANGELOG.md, modules/spreadsheet/etc/startup.m, modules/spreadsheet/functions/csvread.m, modules/spreadsheet/functions/csvwrite.m, modules/spreadsheet/help/en_US/xml/csvread.xml, modules/spreadsheet/help/en_US/xml/csvwrite.xml, modules/spreadsheet/module.iss, modules/spreadsheet/tests/test_csvread.m, modules/spreadsheet/tests/test_csvwrite.m, modules/spreadsheet/tests/test_dlmwrite.m
- Add csvread function to read CSV files
- Add csvwrite function to write CSV files
- Update documentation with new CSV functions
- Add unit tests for CSV read/write operations
- Update module installer and startup files
This adds standard CSV file handling capabilities to the spreadsheet module.
=> feat(spreadsheet): add CSV file read/write support

nelson.nix
Thanks again to  @TLATER
feel free to contribute directly :)
=> chore(NixOS) update after rereview

.github/workflows/ccpp_fedora.yml, BUILDING_Linux.md, CHANGELOG.md, CMake/MpiConfig.cmake, README.md, docker/Dockerfile_Fedora, modules/elementary_functions/src/cpp/Find.cpp, modules/files_folders_functions/functions/ls.m, modules/files_folders_functions/tests/test_ls.m, modules/graphics/functions/colormaplist.m, modules/mex/src/include/MxTypes.h, tools/install_dependencies/install-fedora.sh
=> feat(fedora): fedora 42 support
